#!/usr/bin/env bash
# =============================================================================
# Arch Linux "Niri Edition" — chroot configuration script
# Executed inside arch-chroot by install-niri.sh.
# Variables are supplied via /root/vars.env (generated by the installer).
# =============================================================================

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# LOAD VARIABLES
# ─────────────────────────────────────────────────────────────────────────────
VARS_ENV="/root/vars.env"
[[ -f "${VARS_ENV}" ]] || { echo "[ERROR] vars.env not found"; exit 1; }
# shellcheck source=/dev/null
source "${VARS_ENV}"

DOTFILES="/root/dotfiles"

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────
info()    { echo -e "\033[1;34m[INFO]\033[0m  $*"; }
success() { echo -e "\033[1;32m[OK]\033[0m    $*"; }

# ─────────────────────────────────────────────────────────────────────────────
# pacman
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring pacman (parallel downloads, color)..."
sed -i "s/^#ParallelDownloads.*/ParallelDownloads = ${PARALLEL_DL}/" /etc/pacman.conf
sed -i "s/^#Color/Color/" /etc/pacman.conf

# ─────────────────────────────────────────────────────────────────────────────
# Timezone
# ─────────────────────────────────────────────────────────────────────────────
info "Setting timezone to ${TIMEZONE}..."
ln -sf "/usr/share/zoneinfo/${TIMEZONE}" /etc/localtime
hwclock --systohc

# ─────────────────────────────────────────────────────────────────────────────
# Locale
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring locale (${LOCALE})..."
sed -i "s/^#${LOCALE}/${LOCALE}/" /etc/locale.gen
locale-gen
echo "LANG=${LOCALE}" > /etc/locale.conf

# ─────────────────────────────────────────────────────────────────────────────
# Console keyboard
# ─────────────────────────────────────────────────────────────────────────────
info "Setting console keymap (${KEYMAP})..."
echo "KEYMAP=${KEYMAP}" > /etc/vconsole.conf

# ─────────────────────────────────────────────────────────────────────────────
# Hostname
# ─────────────────────────────────────────────────────────────────────────────
info "Setting hostname to ${HOSTNAME}..."
echo "${HOSTNAME}" > /etc/hostname
cat > /etc/hosts <<EOF
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${HOSTNAME}.localdomain  ${HOSTNAME}
EOF

# ─────────────────────────────────────────────────────────────────────────────
# initramfs
# ─────────────────────────────────────────────────────────────────────────────
info "Generating initramfs..."

# If NVIDIA is installed, add modules to early loading for DRM kernel mode setting
if pacman -Q nvidia-open &>/dev/null || pacman -Q nvidia &>/dev/null; then
  info "  NVIDIA detected: enabling early KMS in initramfs..."
  if ! grep -q '^MODULES=.*nvidia' /etc/mkinitcpio.conf; then
    sed -i 's/^MODULES=(\(.*\))/MODULES=(\1 nvidia nvidia_modeset nvidia_uvm nvidia_drm)/' /etc/mkinitcpio.conf
  fi
fi

mkinitcpio -P

# ─────────────────────────────────────────────────────────────────────────────
# reflector timer
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring reflector service..."
cat > /etc/xdg/reflector/reflector.conf <<EOF
--country Japan
--age 12
--protocol https
--sort rate
--save /etc/pacman.d/mirrorlist
EOF
systemctl enable reflector.timer

# ─────────────────────────────────────────────────────────────────────────────
# zram swap (50% of RAM, zstd)
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring zram swap..."
cat > /etc/systemd/zram-generator.conf <<EOF
[zram0]
zram-size = ram / 2
compression-algorithm = zstd
EOF

# ─────────────────────────────────────────────────────────────────────────────
# GRUB
# ─────────────────────────────────────────────────────────────────────────────
info "Installing GRUB bootloader..."
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg
success "GRUB installed."

# ─────────────────────────────────────────────────────────────────────────────
# User account
# ─────────────────────────────────────────────────────────────────────────────
info "Creating user ${USERNAME}..."
useradd -m -G wheel,audio,video,input,storage,optical -s /bin/bash "${USERNAME}"
echo "${USERNAME}:${USER_PASS}" | chpasswd
passwd -l root
sed -i "s/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/" /etc/sudoers

# ─────────────────────────────────────────────────────────────────────────────
# XDG user directories
# ─────────────────────────────────────────────────────────────────────────────
info "Setting up XDG user directories..."
sudo -u "${USERNAME}" xdg-user-dirs-update

# ─────────────────────────────────────────────────────────────────────────────
# NetworkManager
# ─────────────────────────────────────────────────────────────────────────────
info "Enabling NetworkManager..."
systemctl enable NetworkManager

# ─────────────────────────────────────────────────────────────────────────────
# PipeWire (user services via global preset)
# ─────────────────────────────────────────────────────────────────────────────
info "Enabling PipeWire user services..."
mkdir -p /etc/systemd/user/default.target.wants
for svc in pipewire pipewire-pulse wireplumber; do
  ln -sf "/usr/lib/systemd/user/${svc}.service" \
         "/etc/systemd/user/default.target.wants/${svc}.service"
done

# ─────────────────────────────────────────────────────────────────────────────
# greetd + tuigreet  (session-menu mode)
# tuigreet reads /usr/share/wayland-sessions/*.desktop and presents a menu.
# Both niri and sway install their .desktop files there automatically.
# --remember-session saves the last choice per user.
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring greetd with tuigreet (session menu)..."
mkdir -p /etc/greetd
cat > /etc/greetd/config.toml <<EOF
[terminal]
vt = 1

[default_session]
command = "tuigreet --time --greeting 'Welcome' --sessions /usr/share/wayland-sessions --remember --remember-session"
user = "greeter"
EOF
systemctl enable greetd

# ─────────────────────────────────────────────────────────────────────────────
# fcitx5 environment variables
# ─────────────────────────────────────────────────────────────────────────────
info "Configuring fcitx5 environment variables..."
mkdir -p /etc/environment.d
cat > /etc/environment.d/fcitx5.conf <<EOF
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
EOF

# ─────────────────────────────────────────────────────────────────────────────
# Autostart entries (fcitx5, nm-applet)
# ─────────────────────────────────────────────────────────────────────────────
info "Writing autostart entries (fcitx5, nm-applet)..."
AUTOSTART_DIR="/home/${USERNAME}/.config/autostart"
mkdir -p "${AUTOSTART_DIR}"

cat > "${AUTOSTART_DIR}/fcitx5.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Fcitx5
Exec=fcitx5 -d
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
EOF

cat > "${AUTOSTART_DIR}/nm-applet.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Network Manager Applet
Exec=nm-applet
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
EOF

# ─────────────────────────────────────────────────────────────────────────────
# Deploy dotfiles  (config/* → ~/.config/<app>/)
# ─────────────────────────────────────────────────────────────────────────────
info "Deploying config files to /home/${USERNAME}/.config/..."
HOME_CFG="/home/${USERNAME}/.config"

for app_dir in "${DOTFILES}"/*/; do
  app="$(basename "${app_dir}")"
  dest="${HOME_CFG}/${app}"
  mkdir -p "${dest}"
  cp -r "${app_dir}/." "${dest}/"
  info "  Deployed: ~/.config/${app}/"
done

chown -R "${USERNAME}:${USERNAME}" "${HOME_CFG}"
success "All config files deployed."

# ─────────────────────────────────────────────────────────────────────────────
# fastfetch shell greeting
# ─────────────────────────────────────────────────────────────────────────────
info "Setting fastfetch as shell greeting..."
BASH_PROFILE="/home/${USERNAME}/.bash_profile"
grep -q fastfetch "${BASH_PROFILE}" 2>/dev/null || echo 'fastfetch' >> "${BASH_PROFILE}"
chown "${USERNAME}:${USERNAME}" "${BASH_PROFILE}"

success "=== Chroot configuration complete ==="
